### ISSUE TITLE
Adding support for regtest and writing unit tests

### ISSUE THREAD

**Issue by hwnprsd** [bestinslot-xyz/OPI#7]
Some minor changes to the indexer can support regtest, and that can be used to do some unit testing before the release of any new version. Is this something in the backlog already? Happy to support

**Comment by samedcildir** [comment]
Yes we'll definitely support regtest/testnet etc. it's in our backlog and will probably be released next week.

For testing, unit tests would be great but we already make a full index from scratch before every release and check the results which already includes a lot of the possible unit tests since users sent all kinds of different transaction types / combinations already.

**Comment by hwnprsd** [comment]
Unit tests can make merging PRs much easier, once when all the bull market developers start showing up

**Comment by samedcildir** [comment]
Will definitely add to the todo list, any help is appreciated though

**Comment by samedcildir** [comment]
added NETWORK_TYPE selection via .env 👍
